"""Config file discovery, formats, and the generated defaults."""

from __future__ import annotations

import json

import pytest

from jarvis.config import CONFIG_FILES, Config, find_config_file, project_root, read_config_file


def test_shipped_defaults_match_the_code():
    """config/defaults.json is generated by `jarvis config --defaults --write`.

    A hand-maintained example goes stale the first time anyone changes a default,
    which it repeatedly did. This fails instead.
    """
    path = project_root() / "config" / "defaults.json"
    assert path.is_file(), "run: jarvis config --defaults --write"
    assert json.loads(path.read_text(encoding="utf-8")) == Config().as_dict(), (
        "config/defaults.json is out of date - regenerate it with "
        "`jarvis config --defaults --write`"
    )


def test_as_dict_is_json_serialisable():
    blob = json.dumps(Config().as_dict())
    assert json.loads(blob) == Config().as_dict()
    assert isinstance(json.loads(blob)["wake"]["words"], list), "tuples become lists"


def test_json_config_is_read(tmp_path):
    path = tmp_path / "jarvis.json"
    path.write_text(json.dumps({"log_level": "DEBUG", "stt": {"backend": "google"}}))
    config = Config.load(path=path, environ={})
    assert config.log_level == "DEBUG"
    assert config.stt.backend == "google"
    assert config.stt.whisper_model == "base.en", "untouched defaults survive"


def test_toml_still_works(tmp_path):
    """Anyone who already had a jarvis.toml should not have to move it."""
    path = tmp_path / "jarvis.toml"
    path.write_text('log_level = "WARNING"\n[audio]\npause_threshold = 3.0\n')
    config = Config.load(path=path, environ={})
    assert config.log_level == "WARNING"
    assert config.audio.pause_threshold == 3.0


def test_an_empty_json_file_is_not_an_error(tmp_path):
    path = tmp_path / "jarvis.json"
    path.write_text("")
    assert Config.load(path=path, environ={}) == Config()


def test_config_dir_is_searched_before_the_root(tmp_path, monkeypatch):
    monkeypatch.setenv("JARVIS_HOME", str(tmp_path))
    monkeypatch.delenv("JARVIS_CONFIG", raising=False)
    (tmp_path / "jarvis.toml").write_text('log_level = "ERROR"')
    assert find_config_file(tmp_path).name == "jarvis.toml"

    (tmp_path / "config").mkdir()
    (tmp_path / "config" / "jarvis.json").write_text("{}")
    found = find_config_file(tmp_path)
    assert found.parent.name == "config" and found.suffix == ".json"


def test_no_config_file_is_fine(tmp_path, monkeypatch):
    monkeypatch.delenv("JARVIS_CONFIG", raising=False)
    assert find_config_file(tmp_path) is None
    assert Config.load(path=None, environ={}) is not None


def test_an_explicit_path_overrides_the_search(tmp_path, monkeypatch):
    elsewhere = tmp_path / "somewhere-else.json"
    elsewhere.write_text(json.dumps({"log_level": "DEBUG"}))
    monkeypatch.setenv("JARVIS_CONFIG", str(elsewhere))
    assert find_config_file(tmp_path) == elsewhere


def test_a_missing_explicit_path_is_reported_as_absent(tmp_path, monkeypatch):
    monkeypatch.setenv("JARVIS_CONFIG", str(tmp_path / "nope.json"))
    assert find_config_file(tmp_path) is None


@pytest.mark.parametrize("name", CONFIG_FILES)
def test_every_searched_name_can_actually_be_parsed(tmp_path, name):
    path = tmp_path / name
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("{}" if path.suffix == ".json" else "")
    assert read_config_file(path) == {}


def test_a_broken_json_config_says_so(tmp_path):
    path = tmp_path / "jarvis.json"
    path.write_text("{not json")
    with pytest.raises(json.JSONDecodeError):
        Config.load(path=path, environ={})


def test_underscore_keys_are_notes_not_settings(tmp_path):
    """JSON has no comments. Without somewhere to write down why a setting is
    what it is, it just gets changed back."""
    path = tmp_path / "jarvis.json"
    path.write_text(
        json.dumps(
            {
                "_note": "why this machine differs",
                "stt": {"_why": "GPU is free here", "whisper_model": "small.en"},
            }
        )
    )
    config = Config.load(path=path, environ={})
    assert config.stt.whisper_model == "small.en"


def test_a_genuine_typo_is_still_rejected(tmp_path):
    path = tmp_path / "jarvis.json"
    path.write_text(json.dumps({"stt": {"whisper_modle": "small.en"}}))
    with pytest.raises(ValueError, match="whisper_modle"):
        Config.load(path=path, environ={})
