"""Config file discovery, formats, and the generated defaults."""

from __future__ import annotations

import json

import pytest

from jarvis.config import CONFIG_FILES, Config, find_config_file, project_root, read_config_file


def test_shipped_defaults_match_the_code():
    """config/defaults.json is generated by `jarvis config --defaults --write`.

    A hand-maintained example goes stale; this fails instead.
    """
    path = project_root() / "config" / "defaults.json"
    assert path.is_file(), "run: jarvis config --defaults --write"
    assert json.loads(path.read_text(encoding="utf-8")) == Config().as_dict(), (
        "config/defaults.json is out of date - regenerate it with "
        "`jarvis config --defaults --write`"
    )


def test_the_version_is_read_from_pyproject():
    """It used to be written out in both places and they drifted to 0.6.13 and
    0.6.10 - three releases advertising the wrong number to every client."""
    import tomllib

    from jarvis import __version__

    pyproject = tomllib.loads((project_root() / "pyproject.toml").read_text(encoding="utf-8"))
    assert pyproject["project"]["version"] == __version__


def test_a_bumped_pyproject_is_picked_up_without_reinstalling(tmp_path):
    """Editable installs record the version at sync time, so reading the
    metadata instead would go stale on every bump until the next `uv sync`."""
    from jarvis import _version_in

    (tmp_path / "pyproject.toml").write_text('[project]\nversion = "9.9.9"\n')
    assert _version_in(tmp_path) == "9.9.9"


def test_a_checkout_without_a_pyproject_falls_through(tmp_path):
    from jarvis import _version_in

    assert _version_in(tmp_path) is None
    (tmp_path / "pyproject.toml").write_text('[project]\nname = "jarvis"\n')
    assert _version_in(tmp_path) is None, "no version key is the same as no file"


def test_as_dict_is_json_serialisable():
    blob = json.dumps(Config().as_dict())
    assert json.loads(blob) == Config().as_dict()
    assert "acknowledgements" not in json.loads(blob)["service"], "the timer is gone"


def test_json_config_is_read(tmp_path):
    path = tmp_path / "jarvis.json"
    path.write_text(json.dumps({"log_level": "DEBUG", "stt": {"backend": "google"}}))
    config = Config.load(path=path, environ={})
    assert config.log_level == "DEBUG"
    assert config.stt.backend == "google"
    assert config.stt.whisper_model == "base.en", "untouched defaults survive"


def test_toml_still_works(tmp_path):
    """Anyone who already had a jarvis.toml should not have to move it."""
    path = tmp_path / "jarvis.toml"
    path.write_text('log_level = "WARNING"\n[audio]\npause_threshold = 3.0\n')
    config = Config.load(path=path, environ={})
    assert config.log_level == "WARNING"
    assert config.audio.pause_threshold == 3.0


def test_an_empty_json_file_is_not_an_error(tmp_path):
    path = tmp_path / "jarvis.json"
    path.write_text("")
    assert Config.load(path=path, environ={}) == Config()


def test_config_dir_is_searched_before_the_root(tmp_path, monkeypatch):
    monkeypatch.setenv("JARVIS_HOME", str(tmp_path))
    monkeypatch.delenv("JARVIS_CONFIG", raising=False)
    (tmp_path / "jarvis.toml").write_text('log_level = "ERROR"')
    assert find_config_file(tmp_path).name == "jarvis.toml"

    (tmp_path / "config").mkdir()
    (tmp_path / "config" / "jarvis.json").write_text("{}")
    found = find_config_file(tmp_path)
    assert found.parent.name == "config" and found.suffix == ".json"


def test_no_config_file_is_fine(tmp_path, monkeypatch):
    monkeypatch.delenv("JARVIS_CONFIG", raising=False)
    assert find_config_file(tmp_path) is None
    assert Config.load(path=None, environ={}) is not None


def test_an_explicit_path_overrides_the_search(tmp_path, monkeypatch):
    elsewhere = tmp_path / "somewhere-else.json"
    elsewhere.write_text(json.dumps({"log_level": "DEBUG"}))
    monkeypatch.setenv("JARVIS_CONFIG", str(elsewhere))
    assert find_config_file(tmp_path) == elsewhere


def test_a_missing_explicit_path_is_reported_as_absent(tmp_path, monkeypatch):
    monkeypatch.setenv("JARVIS_CONFIG", str(tmp_path / "nope.json"))
    assert find_config_file(tmp_path) is None


@pytest.mark.parametrize("name", CONFIG_FILES)
def test_every_searched_name_can_actually_be_parsed(tmp_path, name):
    path = tmp_path / name
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("{}" if path.suffix == ".json" else "")
    assert read_config_file(path) == {}


def test_a_broken_json_config_says_so(tmp_path):
    path = tmp_path / "jarvis.json"
    path.write_text("{not json")
    with pytest.raises(json.JSONDecodeError):
        Config.load(path=path, environ={})


def test_underscore_keys_are_notes_not_settings(tmp_path):
    """JSON has no comments. Without somewhere to write down why a setting is
    what it is, it just gets changed back."""
    path = tmp_path / "jarvis.json"
    path.write_text(
        json.dumps(
            {
                "_note": "why this machine differs",
                "stt": {"_why": "GPU is free here", "whisper_model": "small.en"},
            }
        )
    )
    config = Config.load(path=path, environ={})
    assert config.stt.whisper_model == "small.en"


def test_a_genuine_typo_is_still_rejected(tmp_path):
    path = tmp_path / "jarvis.json"
    path.write_text(json.dumps({"stt": {"whisper_modle": "small.en"}}))
    with pytest.raises(ValueError, match="whisper_modle"):
        Config.load(path=path, environ={})


def test_no_config_file_means_everything_is_active():
    """Plug and play: a fresh clone with no config file gets the whole feature
    set. Nothing worth having should need a file to be created first."""
    config = Config.load(path=None, environ={})
    assert config.screen.control is True, "clicking and typing, not only looking"
    assert config.screen.marks_file, "the marked screenshot has somewhere to go"
    assert config.audio.echo_cancellation is True, "it does not transcribe the speakers"
    assert config.audio.listen_while_speaking is True, "so it can be interrupted"
    assert config.service.hotkey, "the toggle key is bound"
    assert config.service.start_webapp is True, "a phone can be the microphone"


def test_the_annotated_example_says_exactly_what_the_defaults_are():
    """`config/jarvis.toml.example` is hand-written prose around real values, so
    it drifts. Copying it must be a no-op: if it disagrees with the defaults then
    one of the two is lying about what you get.

    The two options TOML cannot express are absent from it and keep their
    defaults, which is why this compares equal rather than key by key.
    """
    example = project_root() / "config" / "jarvis.toml.example"
    assert Config.load(path=example, environ={}) == Config(), (
        "config/jarvis.toml.example no longer matches the built-in defaults"
    )
